### ISSUE TITLE
Problem with skill's response

### ISSUE THREAD

**Issue by jojo3632** [EtienneMD/Alexa-Ecovacs#1]
Hi Etienne,

This is exactly what I was looking for.
Thank you so much for putting this together.

Although I'm not a Pyhton expert, I have two working custom Alexa skills. So I have done this before. I followed all your instructions. The Lambda function is set up and linked to the Alexa skill both default region and north america. The skill builder checklist is all green. But when I try the command, I get the following response: "there was a problem with the requested skill's response". 

In the test, I get the following from the skill i/o log input:
```
{
	"version": "1.0",
	"session": {
		"new": true,
		"sessionId": "amzn1.echo-api.session.c4de319e-4ab6-4ef1-8c4a-5a5be897bda9",
		"application": {
			"applicationId": "amzn1.ask.skill.54d3c756-8dc2-40d9-9ab4-fa6cd68a5062"
		},
		"user": {
			"userId": "amzn1.ask.account.AH5K766CW7PDCEBDQX6OZT62G5PEG2MIMTCZQMZMNRY5A5UC3IHQJNRKGDVGC2ITOEAIAAXUTJVB4BPGO4LW5NXXSQZNTRAXQVGTHIWRTEJI3EH62DHYYU4CBE3EBVD5XFTQXQZA2KPMU5ZYIFQTA5QHTRUOQNG55G5ETLTIZQKJMBE4LOW5VITOX7FX6ZPZIJCL4VWIKRH5AXY"
		}
	},
	"context": {
		"AudioPlayer": {
			"playerActivity": "IDLE"
		},
		"Display": {},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.54d3c756-8dc2-40d9-9ab4-fa6cd68a5062"
			},
			"user": {
				"userId": "amzn1.ask.account.AH5K766CW7PDCEBDQX6OZT62G5PEG2MIMTCZQMZMNRY5A5UC3IHQJNRKGDVGC2ITOEAIAAXUTJVB4BPGO4LW5NXXSQZNTRAXQVGTHIWRTEJI3EH62DHYYU4CBE3EBVD5XFTQXQZA2KPMU5ZYIFQTA5QHTRUOQNG55G5ETLTIZQKJMBE4LOW5VITOX7FX6ZPZIJCL4VWIKRH5AXY"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AG7CMCJYRRZ2WXOGAMTINVRQBBONTQZ5S5VI6UEAI3RPL3JZLD4GPPDFCKYT4LV3XIMQS4FHD32NGO5GJGXMV52656JUZPBDCD6E64MCUJ4HDTBY277NTFEFKAIJBSLAQSJPOLITW3DWMIM2SLKC3CF6HQDHZQMAQVWF5ODTNUQGJPUCELRAK",
				"supportedInterfaces": {
					"AudioPlayer": {},
					"Display": {
						"templateVersion": "1.0",
						"markupVersion": "1.0"
					}
				}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjU0ZDNjNzU2LThkYzItNDBkOS05YWI0LWZhNmNkNjhhNTA2MiIsImV4cCI6MTUyMzI5NjQzNywiaWF0IjoxNTIzMjkyODM3LCJuYmYiOjE1MjMyOTI4MzcsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUc3Q01DSllSUloyV1hPR0FNVElOVlJRQkJPTlRRWjVTNVZJNlVFQUkzUlBMM0paTEQ0R1BQREZDS1lUNExWM1hJTVFTNEZIRDMyTkdPNUdKR1hNVjUyNjU2SlVaUEJEQ0Q2RTY0TUNVSjRIRFRCWTI3N05URkVGS0FJSkJTTEFRU0pQT0xJVFczRFdNSU0yU0xLQzNDRjZIUURIWlFNQVFWV0Y1T0RUTlVRR0pQVUNFTFJBSyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFINUs3NjZDVzdQRENFQkRRWDZPWlQ2Mkc1UEVHMk1JTVRDWlFNWk1OUlk1QTVVQzNJSFFKTlJLR0RWR0MySVRPRUFJQUFYVVRKVkI0QlBHTzRMVzVOWFhTUVpOVFJBWFFWR1RISVdSVEVKSTNFSDYyREhZWVU0Q0JFM0VCVkQ1WEZUUVhRWkEyS1BNVTVaWUlGUVRBNVFIVFJVT1FORzU1RzVFVExUSVpRS0pNQkU0TE9XNVZJVE9YN0ZYNlpQWklKQ0w0VldJS1JINUFYWSJ9fQ.G-OU8rReighh5QbWDIypaDgaLs9Pox4bH7U5ec5IRjhd4hUyZZ8VJsEknRHK1DzXj1YgcKCUFvO0zM4opF_I1M-MGWVxQWSygjG-2CcDkwPa-I6lkapICL1Fnoh7ZPCzYc0h5IVngZ-ZmQ8Vuqja7UAfUgLL3WCYdL5xRPprfvcPCKuAeBu3ruDapR_PfgZynDXr8Y50ksmPwGrsSMPa7oNs4MHv5AFU_AOnu0P2FH-zh-vB_rNEEIXeaoaR_Pxzo5wwaGDsKwx3TWaTCMuKNODd4UaOPmzdub2xebYLbA0LFDE88wai3ZdH0Ri2Amh5HoRHgfeoKtzAwq5yRlbSmw"
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.1bcfd478-8d22-494c-9f19-1897132cf5ab",
		"timestamp": "2018-04-09T16:53:57Z",
		"locale": "en-US",
		"intent": {
			"name": "CleanIntent",
			"confirmationStatus": "NONE"
		}
	}
}
```
The output is just NULL.
I checked the interaction model and it all seems ok.
Can you help?

Jordan.

**Comment by EtienneMD** [comment]
Hi Jordan.
I would be happy to help.
Have you tried taking that request and feeding it to your lambda function directly through the AWS website? Just copy and paste your JSON request in a test event and see what error you are getting.
Let me know how that goes.

Etienne

**Comment by jojo3632** [comment]
Hi Etienne,
I copy and pasted this JSON as is in a new test on the AWS console.
I ran the test and got a this error message: 
`"errorMessage": "2018-04-09T18:31:22.172Z 3181f5da-3c24-11e8-b381-77d62d90a578 Task timed out after 3.00 seconds`"

Here are the details:
`START RequestId: 3181f5da-3c24-11e8-b381-77d62d90a578 Version: $LATEST
event.session.application.applicationId=amzn1.ask.skill.54d3c756-8dc2-40d9-9ab4-fa6cd68a5062
on_session_started requestId=amzn1.echo-api.request.1bcfd478-8d22-494c-9f19-1897132cf5ab, sessionId=amzn1.echo-api.session.c4de319e-4ab6-4ef1-8c4a-5a5be897bda9
on_intent requestId=amzn1.echo-api.request.1bcfd478-8d22-494c-9f19-1897132cf5ab, sessionId=amzn1.echo-api.session.c4de319e-4ab6-4ef1-8c4a-5a5be897bda9
END RequestId: 3181f5da-3c24-11e8-b381-77d62d90a578
REPORT RequestId: 3181f5da-3c24-11e8-b381-77d62d90a578	Duration: 3003.27 ms	Billed Duration: 3000 ms 	Memory Size: 128 MB	Max Memory Used: 43 MB	
2018-04-09T18:31:22.172Z 3181f5da-3c24-11e8-b381-77d62d90a578 Task timed out after 3.00 seconds`

**Comment by EtienneMD** [comment]
Under Basic Settings, try setting timeout to 15 sec. The skill takes a little while to connect to the xmpp server before it can actually send a command to your vacuum, generally around 7 or 8 seconds. 
Thank you for your feedback, I'll be updating the README.

**Comment by jojo3632** [comment]
Hi Etienne,

That did the trick.
It's working now! Thank you so much for your help.

I have two enhancement suggestions:
1. Do you know if there is a command for spot cleaning, e.g. "ask my vacuum to spot clean". From what I could read, the XMPP command is `<ctl td="Clean"><clean type="spot" speed="standard"/></ctl>`

2. Can you add an utterance for timed cleaning (I believe it's already in the 'sucks' code, see line 164 of cli.py).  "ask my vacuum to clean for 20 minutes"

Thanks again.
J.

**Comment by EtienneMD** [comment]
Glad you like it. I can definitely add a spot clean command, I simply did not see a use for it. I am also planning a few more intents, like battery percentage and current status. Keep an eye on the repo for updates. 

While it is true that the CLI offers a timed clean functionality, keep in mind that the Sucks CLI tool is different than the Sucks library, which is what I’m using here. The way the CLI does this, is it sends a clean command, then waits 20 minutes before sending a charge command. That means that your Lambda instance would be running for 20 minutes before it could disconnect, and I’m not sure that’s something you would want. 

Thank you for sharing your ideas. 

Etienne
