### ISSUE TITLE
How to update update 

### ISSUE THREAD

**Issue by jojo3632** [EtienneMD/Alexa-Ecovacs#4]
hi Etienne,

I see you added a few commands (spot, edge, battery status).
How do I update my existing skill? 

Do I simply have to:
1. Replace the interaction json file in the Alexa developer console with the latest one here
2. Upload the new deploy.zip into the Lamdba console.

I want to make sure I'm not breaking the skill I set up with your help back 6 months ago.

Thanks,
Jordan.

**Comment by EtienneMD** [comment]
You are correct, update your Alexa skill's interaction model with the new intents and the lambda function with the new handlers and everything should be already configured. You can add or modify utterances to your liking as well.
